# ConfiguraciÃ³n para las plantillas de issues
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

blank_issues_enabled: false
contact_links:
  - name: ğŸ“š DocumentaciÃ³n
    url: https://github.com/miguelnexs/localix/wiki
    about: Revisa la documentaciÃ³n antes de crear un issue
  - name: ğŸ’¬ Discusiones
    url: https://github.com/miguelnexs/localix/discussions
    about: Preguntas generales y discusiones
  - name: ğŸ“ Soporte
    url: https://github.com/miguelnexs/localix/blob/main/.github/SUPPORT.md
    about: GuÃ­a de soporte y contacto
